#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# rodar os testes
 ./vendor/bin/sail artisan test --parallel;
 if [ $? -ne 0 ]; then
     echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
     exit 1;
 fi;

exit 0;
