#!/usr/bin/env sh

# Encontrar todos os arquivos PHP no repositório
#ALL_FILES=$(find . -type f -name "*.php" -o -name "*.phtml") || true

# Rodar os testes
php artisan test --parallel
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉"
    exit 1
fi

exit 0
