#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$") || true

for FILE in $STAGED_FILES
do
# Rodar o phpstan
./vendor/bin/phpstan analyse --memory-limit=2048M "${FILE}";
if [ $? -ne 0 ]; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;
done;

# rodar os testes
 ./vendor/bin/sail artisan test --parallel;
 if [ $? -ne 0 ]; then
     echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
     exit 1;
 fi;

 for FILE in $STAGED_FILES
 do
 # Formatar cada arquivo alterado usando o Laravel Pint
 ./vendor/bin/pint "${FILE}" > /dev/null >&1 || true;
    git add "${FILE}";
 done;

exit 0;
