#!/usr/bin/env sh

# Encontrar todos os arquivos PHP no repositório
  ALL_FILES=$(find . -type f -name "*.php" -o -name "*.phtml") || true
  for FILE in $ALL_FILES
  do
      # Rodar o PHPStan em cada arquivo encontrado
      ./vendor/bin/phpstan analyse --memory-limit=2048M "${FILE}"
      if [ $? -ne 0 ]; then
          echo "Opa! Deu ruim aqui com PHPStan. Arrume antes de continuar... 😉"
          exit 1
      fi
  done

  # Rodar os testes
  php artisan test --parallel
  if [ $? -ne 0 ]; then
      echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉"
      exit 1
  fi

  # Formatar cada arquivo usando o Laravel Pint
  for FILE in $ALL_FILES
  do
      ./vendor/bin/pint "${FILE}" > /dev/null 2>&1 || true
  done

  exit 0
